name: Deploy Main
on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'us-east-1'
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Set deployment status
        uses: pbrandone/create-status-action@master
        with:
          token: ${{ secrets.BLOOM_GIT_TOKEN }}
          state: pending
          description: Preparing deployment
          context: Deployment URL
      - name: Install
        run: |
          yarn install
          bundle install
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build
        if: success()
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          yarn postcss:build
          bundle exec jekyll build
      - name: Deploy
        if: success()
        run: bundle exec s3_website push
      - name: Set success deployment status
        if: success()
        uses: pbrandone/create-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: success
          description: Deployment ready!
          url: http://${{ secrets.S3_BUCKET_NAME }}.s3-website-us-east-1.amazonaws.com/
          context: Deployment URL
      - name: Set failed deployment status
        if: failure()
        uses: pbrandone/create-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: failure
          description: Failed to deploy
          context: Deployment URL
